# This file is used by the pretix team internally to coordinate releases of this plugin
[plugin]
package = "pretix-fontpack-free"
modules = [ "pretix_fontpackfree" ]
marketplace_name = "fontpack-free"
pypi = true
repository_servers = { origin = "github.com" }
tag_targets = [ "origin" ]
branch_targets = [ "origin/master" ]

